#ifndef AUDIO_H
#define AUDIO_H

enum class SAMPLETYPE {
    NONE,
    UI_CLICK, UI_SELECT,
    WIN, LOSE,
    ATTACK, COIN_COLLECT, HEART_COLLECT, WOOD_CUT, WOOD_COLLECT, CHEST_OPEN, ITEM_PICKUP,
    SHEEP_PASSIVE, SHEEP_COLLECT,
    PIG_PASSIVE, PIG_COLLECT,
    COW_PASSIVE, COW_COLLECT,
    CHICKEN_PASSIVE, CHICKEN_COLLECT,
    WALK_GRASS, WALK_SAND,
    _WALK_GRASS0, _WALK_GRASS1, _WALK_GRASS2, _WALK_GRASS3,
    _WALK_SAND0, _WALK_SAND1, _WALK_SAND2, _WALK_SAND3
};

void init_audio();
void stop_audio();
void trigger_sound(SAMPLETYPE sample);


#endif // AUDIO_H
